# Generated by Django 5.2.5 on 2025-08-28 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Public Infrastructure', 'Public Infrastructure'), ('Environment', 'Environment'), ('Municipal Guard', 'Municipal Guard'), ('Education', 'Education'), ('Agriculture and Livestocks', 'Agriculture and Livestocks')], max_length=50)),
                ('status', models.CharField(choices=[('under review', 'Under Review'), ('genuine', 'Genuine'), ('rejected', 'Rejected'), ('in-progress', 'In Progress'), ('resolved', 'Resolved')], default='under review', max_length=20)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('authority', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
