# Generated by Django 5.2.5 on 2025-08-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='ward',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
