# Generated by Django 5.2.5 on 2025-08-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='last_threshold_notified',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
