# Generated by Django 5.2.5 on 2025-08-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_alter_complaint_authority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='authority',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
