# Generated by Django 5.2.5 on 2025-08-30 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorities', '0005_remove_authority_token_alter_authority_role'),
        ('complaints', '0005_alter_complaint_authority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authorities.authority'),
        ),
    ]
