# Generated by Django 5.2.5 on 2025-09-01 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_alter_complaint_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='complaint',
            name='response_file',
            field=models.FileField(blank=True, null=True, upload_to='complaint_responses/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='response_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
