# Generated by Django 5.2.5 on 2025-09-02 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_complaint_progress_complaint_response_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('under review', 'Under Review'), ('genuine', 'Genuine'), ('rejected', 'Rejected'), ('in-progress', 'In Progress'), ('resolved', 'Resolved')], max_length=20)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('response_text', models.TextField(blank=True, null=True)),
                ('response_file', models.FileField(blank=True, null=True, upload_to='complaint_responses/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='complaints.complaint')),
            ],
        ),
    ]
