# Generated by Django 5.2.5 on 2025-08-27 14:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authority',
            name='category',
        ),
        migrations.RemoveField(
            model_name='authority',
            name='is_active',
        ),
        migrations.AddField(
            model_name='authority',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='authority',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='authority',
            name='role',
            field=models.CharField(default='authority', max_length=50),
        ),
    ]
