# Generated by Django 5.2.5 on 2025-08-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorities', '0002_remove_authority_category_remove_authority_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='authority',
            name='role',
            field=models.CharField(choices=[('education', 'Education'), ('environment', 'Environment'), ('municipal_guard', 'Municipal Guard'), ('agriculture', 'Agriculture and Livestock'), ('infrastructure', 'Public Infrastructure')], max_length=50),
        ),
    ]
