# Generated by Django 5.2.5 on 2025-08-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorities', '0003_authority_is_active_alter_authority_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='authority',
            name='role',
            field=models.CharField(choices=[('education', 'Education'), ('environment', 'Environment'), ('police', 'Municipal Guard'), ('agriculture', 'Agriculture and Livestock'), ('infrastructure', 'Public Infrastructure')], max_length=50),
        ),
    ]
