# Generated by Django 5.2.5 on 2025-08-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorities', '0004_authority_token_alter_authority_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authority',
            name='token',
        ),
        migrations.AlterField(
            model_name='authority',
            name='role',
            field=models.CharField(choices=[('education', 'Education'), ('environment', 'Environment'), ('police', 'Municipal Guard'), ('agriculture', 'Agriculture and Livestock'), ('infrastructure', 'Public Infrastructure')], default='infrastructure', max_length=50),
        ),
    ]
